---
- name: Ensure data directory exists
  file:
    path: '{{ data_directory }}'
    owner: postgres
    group: postgres
    state: 'directory'
    mode: '0700'
  become: yes
  tags: postgresql-service

- name: Ensure systemd overrides directory exists
  file:
    path: '/etc/systemd/system/postgresql-9.6.service.d'
    state: 'directory'
    mode: '0755'
  become: yes
  tags: postgresql-service

- name: Add systemd service overrides
  template:
    src: 'systemd-override.conf.j2'
    dest: '/etc/systemd/system/postgresql-9.6.service.d/override.conf'
    owner: postgres
    group: postgres
    mode: 0644
  become: yes
  notify:
  - Restart PostgreSQL
  tags: postgresql-service

- name: Initialize postgresql database
  command:
    cmd: '/usr/pgsql-9.6/bin/pg_ctl initdb -D {{ data_directory }}'
    creates: '{{ data_directory }}/postgresql.conf'
  become: yes
  become_user: postgres
  tags: postgresql-service

- name: Install PostgreSQL configuration file
  template:
    src: 'postgresql.conf.j2'
    dest: '{{ data_directory }}/postgresql.conf'
    owner: postgres
    group: postgres
    mode: 0600
  become: yes
  become_user: postgres
  notify:
  - Restart PostgreSQL
  tags: postgresql-service

- name: Ensure that postgres pg_hba entry exists correctly
  postgresql_pg_hba:
    dest: '{{ data_directory }}/pg_hba.conf'
    contype: 'local'
    users: 'postgres'
    source: '127.0.0.1/32'
    databases: 'all'
    method: 'ident'
    create: true
  become: yes
  become_user: postgres
  tags: postgresql-service

- name: Ensure that needed pg_hba entries exist
  postgresql_pg_hba:
    dest: '{{ data_directory }}/pg_hba.conf'
    contype: '{{ item.type }}'
    users: '{{ item.user }}'
    source: '{{ item.address }}'
    databases: '{{ item.database }}'
    method: '{{ item.method }}'
    create: true
  with_items: '{{ allowed_connections }}'
  become: yes
  become_user: postgres
  tags: postgresql-service

- name: Ensure PostgreSQL server is started
  service:
    name: 'postgresql-9.6'
    state: 'started'
    enabled: 'yes'
    daemon_reload: 'yes'
  become: yes
  tags: postgresql-service
